### ISSUE TITLE
API: Endpoint for Slack Authentication 

### ISSUE THREAD

**Issue by dpfernandes** [HackYourFuture-CPH/web-dev-rooms#58]
Create an endpoint that uses the User's Slack ID and Token to authenticate with our app and retrieves the SlackID and Name of the user.

The endpoint could also retrieve the User groups that the specific user is part of, like the class user group.

![image](https://user-images.githubusercontent.com/6642037/99899893-deddb180-2cac-11eb-9591-d3850269c8b2.png)

**Comment by orhantoy** [comment]
@dpfernandes I'm here at the study group with Nuha and it is a bit unclear to both of us what the specific work needed for this issue is. I think the work needed is to integrate with the [Slack API](https://api.slack.com/authentication/basics) but I could be wrong.

Questions:

- What should the endpoint be called? Nuha is using `/api/slack_users` in https://github.com/HackYourFuture-CPH/web-dev-rooms/pull/70 for now.
- Does this endpoint use the database, or is it the idea to use request parameters and communicate with the Slack API?
- Do we need all CRUD endpoints, or are we speaking of just 1 endpoint?
- What is the relation between the screenshot and this issue?

Here's what I think the work needed is but please fill free to correct me or fill in missing pieces:

- Create an endpoint, called something `POST /api/slack/auth`
- This endpoint will accept a token, could be as a parameter in the request body, or in the `Authorization` header
- This token could then be used to call [https://slack.com/api/users.identity](https://api.slack.com/methods/users.identity) to get the user ID and name.
- I'm not yet sure which Slack API endpoint would give the groups a user is in, but that can probably be found in the [method list](https://slack.com/api/users.identity).

And lastly Daniel, it would be nice to understand in which context this endpoint will be used (which screens on the frontend).

**Comment by dpfernandes** [comment]
This issue is to solve the authentication for the app using Slack authentication
It should validate if the user has an account in our slack workspace and if the user is part of any user group so we know it’s part of a class or by default if it’s not they should be considered mentors

I think it’s fine if the endpoint just validates if the user has an account and returns the token

T
he screenshot is to show a user group

I think your approach it fine

Can you elaborate on the this “And lastly Daniel, it would be nice to understand in which context this endpoint will be used (which screens on the frontend).”?

**Comment by orhantoy** [comment]
> Can you elaborate on this

Basically, I mean when would this endpoint be called, and originated from where in the frontend?

**Comment by orhantoy** [comment]
This is the desired behavior I understand from https://github.com/HackYourFuture-CPH/web-dev-rooms/issues/58#issuecomment-733660806:

```
POST /api/slack/auth
Request: { "slackUserId": "xyz" }
Response: { "slackUserId": "xyz", "name": "John Appleseed", "userGroups": [{ "id": "...", "name": "Class 15" }] }
```

It sounds like the Slack authentication token will come from an environment variable.

@dpfernandes Does this sound correct?

**Comment by dpfernandes** [comment]
It seems right! :) 

Any opinions @tpetrina and @bytewiz ?
